# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50b5c6b10452c35ef8001d2bb8827bbea29ebfeacf97a53ba28749a83944c06048f36bb8d835d6367a04485a1ead6906d10d3ff94d0a2f0326843a1111eb424b

test:
  secret_key_base: fb06ba0d8ca65735e50a9bedfc2773e7244632118cce28a6eb4d7c0771e697e63ed37515090cae5fa8ad7485184ef9b5590dc46be6a04266a512bc43c543bd83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
